FROM node:24.12.0-alpine AS development

WORKDIR /app

COPY package*.json ./

# Prisma schema is needed by the postinstall script
COPY prisma ./prisma

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
